level: debug
encoding: console
development: true
disableCaller: false
outputPaths:
  - stdout
errorOutputPaths:
  - stderr
encoderConfig:
  messageKey: message
  levelKey: level
  levelEncoder: capital
  timeKey: time
  timeEncoder: iso8601
  stacktraceKey: stacktrace
  errorKey: error
  callerKey: caller
  callerEncoder: full
